---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataverse-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6G
  selector:
    matchLabels:
      backup: "False"
