apiVersion: v1
kind: Service
metadata:
  name: dataverse-service
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:401375713632:certificate/83e70069-cd63-486c-bbf2-9c7860f183d8
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app.kubernetes.io/component: appserver
    app.kubernetes.io/name: dataverse
    app.kubernetes.io/part-of: dataverse
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8080
  - name: ajp
    port: 8009
    protocol: TCP
    targetPort: 8009
  type: LoadBalancer
