---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: solr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3G
  selector:
    matchLabels:
      backup: "False"
